repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: prettier
        name: prettier (except yaml-typed files)
        language: system
        entry: prettier --write --ignore-unknown
        exclude_types: [yaml]
-   repo: https://github.com/lyz-code/yamlfix
    rev: 1.19.1
    hooks:
    -   id: yamlfix
-   repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
    -   id: taplo-format
    -   id: taplo-lint
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.0
    hooks:
    -   id: editorconfig-checker
